import { createFileRoute, Link } from "@tanstack/react-router";
import { Download, FolderOpen, Save, Trash2 } from "lucide-react";
import { toast } from "sonner";
import { Page } from "@/components/site-chrome";
import {
  AlertDialog,
  AlertDialogAction,
  AlertDialogCancel,
  AlertDialogContent,
  AlertDialogDescription,
  AlertDialogFooter,
  AlertDialogHeader,
  AlertDialogTitle,
  AlertDialogTrigger,
} from "@/components/ui/alert-dialog";
import {
  clearProject,
  inr,
  saveVersion,
  removeItem,
  updateActiveProject,
  totalCost,
  useActiveProject,
} from "@/lib/project-store";

export const Route = createFileRoute("/project")({
  head: () => ({
    meta: [
      { title: "Project Estimate — BuildWise" },
      {
        name: "description",
        content:
          "Combine brick, cement, paint, tile and steel estimates into one project summary, then save it or download a PDF.",
      },
      { property: "og:title", content: "Project Estimate — BuildWise" },
      {
        property: "og:description",
        content: "One material cost summary for your whole construction project.",
      },
      { property: "og:type", content: "website" },
      { name: "twitter:card", content: "summary_large_image" },
    ],
  }),
  component: ProjectPage,
});

function ProjectPage() {
  const project = useActiveProject();

  if (!project) {
    return (
      <Page>
        <div className="text-center py-20">
          <h2 className="text-2xl font-bold">No Active Project</h2>
          <p className="mt-2 text-muted-foreground">
            Go to the dashboard to select or create a project.
          </p>
          <Link
            to="/dashboard"
            className="mt-6 inline-flex rounded-md bg-primary px-4 py-2.5 text-sm font-semibold text-primary-foreground"
          >
            Go to Dashboard
          </Link>
        </div>
      </Page>
    );
  }

  const total = totalCost(project.items);

  async function downloadPdf() {
    const { jsPDF } = await import("jspdf");
    const doc = new jsPDF({ unit: "pt", format: "a4" });
    const left = 56;
    const right = 539;
    const rupees = (n: number) => inr(n).replace("₹", "Rs. ");
    let y = 64;

    // Header band
    doc.setFillColor(23, 61, 122);
    doc.rect(0, 0, 595, 104, "F");
    doc.setTextColor(255, 255, 255);
    doc.setFont("helvetica", "bold");
    doc.setFontSize(24);
    doc.text("BuildWise", left, 52);
    doc.setFont("helvetica", "normal");
    doc.setFontSize(12);
    doc.text("Construction Cost Management Report", left, 74);

    doc.setTextColor(30, 30, 30);
    y = 148;
    doc.setFont("helvetica", "bold");
    doc.setFontSize(11);
    doc.text("Project Name", left, y);
    doc.text("Date Generated", right, y, { align: "right" });
    y += 17;
    doc.setFont("helvetica", "normal");
    doc.setFontSize(12);
    doc.text(project?.name || "Untitled Project", left, y);
    doc.text(
      new Date().toLocaleDateString("en-IN", {
        day: "2-digit",
        month: "short",
        year: "numeric",
      }),
      right,
      y,
      { align: "right" },
    );

    y += 30;
    doc.setDrawColor(210, 216, 224);
    doc.line(left, y, right, y);

    // Table
    y += 30;
    doc.setFont("helvetica", "bold");
    doc.setFontSize(13);
    doc.text("Material Summary", left, y);

    y += 20;
    doc.setFillColor(238, 242, 248);
    doc.rect(left, y - 14, right - left, 24, "F");
    doc.setFontSize(10);
    doc.setTextColor(70, 80, 95);
    doc.text("MATERIAL", left + 10, y + 2);
    doc.text("QUANTITY", 300, y + 2);
    doc.text("ESTIMATED COST", right - 10, y + 2, { align: "right" });

    y += 26;
    doc.setFont("helvetica", "normal");
    doc.setFontSize(11);
    doc.setTextColor(30, 30, 30);
    project?.items.forEach((i, idx) => {
      if (idx % 2 === 1) {
        doc.setFillColor(249, 250, 252);
        doc.rect(left, y - 13, right - left, 24, "F");
      }
      doc.text(i.label, left + 10, y + 3);
      doc.text(i.quantity, 300, y + 3);
      doc.text(rupees(i.cost), right - 10, y + 3, { align: "right" });
      y += 24;
    });

    y += 6;
    doc.setDrawColor(210, 216, 224);
    doc.line(left, y, right, y);

    y += 12;
    doc.setFillColor(23, 61, 122);
    doc.rect(left, y, right - left, 40, "F");
    doc.setTextColor(255, 255, 255);
    doc.setFont("helvetica", "bold");
    doc.setFontSize(12);
    doc.text("Total Estimated Material Cost", left + 12, y + 25);
    doc.setFontSize(14);
    doc.text(rupees(total), right - 12, y + 25, { align: "right" });

    // Footer
    doc.setFont("helvetica", "normal");
    doc.setFontSize(9);
    doc.setTextColor(130, 138, 150);
    doc.text("Generated by BuildWise Version 1.0", left, 800);
    doc.text(
      "Estimates are indicative and exclude labour, taxes and wastage beyond stated allowances.",
      left,
      814,
    );

    doc.save(`${project?.name.replace(/[^\w\- ]+/g, "") || "project"}-estimate.pdf`);
    toast.success("PDF generated successfully.");
  }

  return (
    <Page>
      <header className="max-w-2xl">
        <h1 className="text-4xl font-bold tracking-tight sm:text-5xl">Project Estimate</h1>
        <p className="mt-4 text-base leading-relaxed text-muted-foreground">
          Every calculator can send its result here. Name your project, review the material
          breakdown and export it as a PDF.
        </p>
      </header>

      <div className="mt-10 grid gap-6 lg:grid-cols-[1.2fr_0.8fr]">
        <section className="rounded-lg border border-border bg-card p-6 shadow-[var(--shadow-soft)] sm:p-8">
          <label className="block">
            <span className="text-sm font-semibold uppercase tracking-widest text-muted-foreground">
              Project name
            </span>
            <input
              value={project.name}
              onChange={(e) => updateActiveProject({ name: e.target.value })}
              placeholder="My House"
              className="mt-2 w-full rounded-md border border-input bg-background px-3.5 py-2.5 text-base font-medium outline-none transition-shadow focus:border-ring focus:ring-4 focus:ring-ring/15"
            />
          </label>

          <div className="mt-8 space-y-3">
            {project.items.length === 0 ? (
              <div className="rounded-lg border border-dashed border-border px-6 py-12 text-center">
                <FolderOpen size={26} className="mx-auto text-muted-foreground" />
                <p className="mt-4 text-sm text-muted-foreground">
                  No materials added yet. Open a calculator and choose “Add to project”.
                </p>
                <Link
                  to="/calculators"
                  className="mt-5 inline-flex rounded-md bg-primary px-4 py-2.5 text-sm font-semibold text-primary-foreground"
                >
                  Browse calculators
                </Link>
              </div>
            ) : (
              project.items.map((i) => (
                <div
                  key={i.slug}
                  className="flex items-center justify-between gap-4 rounded-md bg-secondary px-4 py-3.5"
                >
                  <div className="min-w-0">
                    <p className="truncate text-sm font-semibold">{i.label}</p>
                    <p className="text-sm text-muted-foreground tabular-nums">{i.quantity}</p>
                  </div>
                  <div className="flex items-center gap-3">
                    <span className="text-base font-semibold tabular-nums">{inr(i.cost)}</span>
                    <button
                      type="button"
                      aria-label={`Remove ${i.label}`}
                      onClick={() => removeItem(i.slug)}
                      className="grid h-8 w-8 place-items-center rounded-lg text-muted-foreground transition-colors hover:bg-background hover:text-foreground"
                    >
                      <Trash2 size={16} />
                    </button>
                  </div>
                </div>
              ))
            )}
          </div>
        </section>

        <section className="h-fit rounded-lg border border-border bg-card p-6 shadow-[var(--shadow-soft)] sm:p-8">
          <h2 className="text-sm font-semibold uppercase tracking-widest text-muted-foreground">
            Summary
          </h2>
          <div className="mt-6 rounded-md bg-primary px-5 py-6 text-primary-foreground">
            <p className="text-sm font-medium opacity-90">Total estimated material cost</p>
            <p className="mt-2 text-3xl font-bold tabular-nums">{inr(total)}</p>
            <p className="mt-2 text-xs opacity-80">
              {project.items.length} material{project.items.length === 1 ? "" : "s"} included
            </p>
          </div>

          <div className="mt-6 grid gap-3">
            <button
              type="button"
              disabled={project.items.length === 0}
              onClick={downloadPdf}
              className="inline-flex items-center justify-center gap-2 rounded-md border border-border bg-background px-4 py-2.5 text-sm font-semibold transition-colors hover:bg-secondary disabled:opacity-50"
            >
              <Download size={16} /> Download PDF
            </button>
            <button
              type="button"
              disabled={project.items.length === 0}
              onClick={() => {
                saveVersion();
                toast.success("Project version saved successfully.");
              }}
              className="inline-flex items-center justify-center gap-2 rounded-md bg-primary px-4 py-2.5 text-sm font-semibold text-primary-foreground transition-opacity hover:opacity-90 disabled:opacity-50"
            >
              <Save size={16} /> Save Version
            </button>
            {project.items.length > 0 && (
              <AlertDialog>
                <AlertDialogTrigger asChild>
                  <button
                    type="button"
                    className="text-xs font-medium text-muted-foreground underline-offset-4 hover:underline"
                  >
                    Clear all materials
                  </button>
                </AlertDialogTrigger>
                <AlertDialogContent>
                  <AlertDialogHeader>
                    <AlertDialogTitle>
                      Are you sure you want to clear this project?
                    </AlertDialogTitle>
                    <AlertDialogDescription>
                      All added materials will be removed and the total reset to ₹0. The project
                      name is kept.
                    </AlertDialogDescription>
                  </AlertDialogHeader>
                  <AlertDialogFooter>
                    <AlertDialogCancel>Cancel</AlertDialogCancel>
                    <AlertDialogAction
                      onClick={() => {
                        clearProject();
                        toast.success("Project cleared successfully.");
                      }}
                    >
                      Yes, clear it
                    </AlertDialogAction>
                  </AlertDialogFooter>
                </AlertDialogContent>
              </AlertDialog>
            )}
          </div>

          {project.savedAt && (
            <p className="mt-5 text-xs text-muted-foreground">
              Last saved {new Date(project.savedAt).toLocaleString()}
            </p>
          )}
        </section>
      </div>
    </Page>
  );
}
