import { createFileRoute, Link } from "@tanstack/react-router";
import { Download, FileSpreadsheet } from "lucide-react";
import { toast } from "sonner";
import { Page } from "@/components/site-chrome";
import { useActiveProject, totalCost, inr, updateActiveProject } from "@/lib/project-store";
import { useMaterialStore } from "@/lib/material-store";

export const Route = createFileRoute("/reports")({
  component: ReportsPage,
});

function ReportsPage() {
  const project = useActiveProject();
  const { prices } = useMaterialStore();

  if (!project) {
    return (
            <Page>
        <div className="text-center py-20">
          <h2 className="text-2xl font-bold">No Active Project</h2>
          <p className="mt-2 text-muted-foreground">
            Go to the dashboard to select or create a project.
          </p>
          <Link
            to="/dashboard"
            className="mt-6 inline-flex rounded-md bg-primary px-4 py-2.5 text-sm font-semibold text-primary-foreground transition-colors hover:bg-primary/90"
          >
            Go to Dashboard
          </Link>
        </div>
      </Page>
    );
  }

  const materialCost = totalCost(project.items);
  const labourCost = materialCost * 0.4;
  const contingency = (materialCost + labourCost) * 0.05;
  const totalProjectCost = materialCost + labourCost + contingency;

  async function downloadPdf() {
    const { jsPDF } = await import("jspdf");
    const doc = new jsPDF({ unit: "pt", format: "a4" });
    const left = 56;
    const right = 539;
    const rupees = (n: number) => inr(n).replace("₹", "Rs. ");
    let y = 64;

    // Header band
    doc.setFillColor(23, 61, 122);
    doc.rect(0, 0, 595, 104, "F");
    doc.setTextColor(255, 255, 255);
    doc.setFont("helvetica", "bold");
    doc.setFontSize(24);
    doc.text("BUILDWISE PROFESSIONAL", left, 52);
    doc.setFont("helvetica", "normal");
    doc.setFontSize(12);
    doc.text("Detailed Construction Cost Report", left, 74);

    doc.setTextColor(30, 30, 30);
    y = 148;
    doc.setFont("helvetica", "bold");
    doc.setFontSize(11);
    doc.text("Project Details", left, y);
    doc.text("Date Generated", right, y, { align: "right" });

    y += 17;
    doc.setFont("helvetica", "normal");
    doc.setFontSize(12);
    doc.text(`Name: ${project?.name || "Untitled Project"}`, left, y);
    doc.text(
      new Date().toLocaleDateString("en-IN", {
        day: "2-digit",
        month: "short",
        year: "numeric",
      }),
      right,
      y,
      { align: "right" },
    );

    y += 17;
    doc.text(`Client: ${project?.clientName || "N/A"}`, left, y);
    y += 17;
    doc.text(`Location: ${project?.location || "N/A"}`, left, y);

    y += 30;
    doc.setDrawColor(210, 216, 224);
    doc.line(left, y, right, y);

    // Table
    y += 30;
    doc.setFont("helvetica", "bold");
    doc.setFontSize(13);
    doc.text("Bill of Quantities (BOQ)", left, y);

    y += 20;
    doc.setFillColor(238, 242, 248);
    doc.rect(left, y - 14, right - left, 24, "F");
    doc.setFontSize(10);
    doc.setTextColor(70, 80, 95);
    doc.text("ITEM", left + 10, y + 2);
    doc.text("QTY", 250, y + 2);
    doc.text("RATE", 350, y + 2);
    doc.text("AMOUNT", right - 10, y + 2, { align: "right" });

    y += 26;
    doc.setFont("helvetica", "normal");
    doc.setFontSize(11);
    doc.setTextColor(30, 30, 30);
    project?.items.forEach((i, idx) => {
      if (idx % 2 === 1) {
        doc.setFillColor(249, 250, 252);
        doc.rect(left, y - 13, right - left, 24, "F");
      }
      doc.text(i.label, left + 10, y + 3);
      doc.text(i.quantity, 250, y + 3);
      doc.text(rupees(i.rate || 0), 350, y + 3);
      doc.text(rupees(i.cost), right - 10, y + 3, { align: "right" });
      y += 24;
    });

    y += 6;
    doc.setDrawColor(210, 216, 224);
    doc.line(left, y, right, y);

    // Summary
    y += 20;
    doc.setFont("helvetica", "bold");
    doc.text("Cost Summary", left, y);

    y += 16;
    doc.setFont("helvetica", "normal");
    doc.text("Total Material Cost:", left, y);
    doc.text(rupees(materialCost), right, y, { align: "right" });

    y += 16;
    doc.text("Total Labour Cost (Est. 40%):", left, y);
    doc.text(rupees(labourCost), right, y, { align: "right" });

    y += 16;
    doc.text("Contingency (5%):", left, y);
    doc.text(rupees(contingency), right, y, { align: "right" });

    y += 20;
    doc.setFillColor(23, 61, 122);
    doc.rect(left, y, right - left, 40, "F");
    doc.setTextColor(255, 255, 255);
    doc.setFont("helvetica", "bold");
    doc.setFontSize(12);
    doc.text("Total Estimated Project Cost", left + 12, y + 25);
    doc.setFontSize(14);
    doc.text(rupees(totalProjectCost), right - 12, y + 25, { align: "right" });

    // Footer
    doc.setFont("helvetica", "normal");
    doc.setFontSize(9);
    doc.setTextColor(130, 138, 150);
    doc.text("Generated by BuildWise Professional", left, 800);

    doc.save(`${project?.name.replace(/[^\w\- ]+/g, "") || "project"}-report.pdf`);
    toast.success("PDF generated successfully.");
  }

  function downloadCsv() {
    const headers = ["Item Description", "Quantity", "Unit", "Rate", "Amount"];
    const rows = project!.items.map((i) => [
      i.label,
      parseFloat(i.quantity) || 0,
      i.unit || "",
      i.rate || 0,
      i.cost,
    ]);

    const csvContent =
      "data:text/csv;charset=utf-8," +
      headers.join(",") +
      "\n" +
      rows.map((e) => e.join(",")).join("\n");

    const encodedUri = encodeURI(csvContent);
    const link = document.createElement("a");
    link.setAttribute("href", encodedUri);
    link.setAttribute(
      "download",
      `${project!.name.replace(/[^\w\- ]+/g, "") || "project"}-boq.csv`,
    );
    document.body.appendChild(link);
    link.click();
    document.body.removeChild(link);
    toast.success("CSV generated successfully.");
  }

  return (
    <Page>
      <header className="max-w-2xl">
        <h1 className="text-4xl font-bold tracking-tight sm:text-5xl">Professional Reports</h1>
        <p className="mt-4 text-base leading-relaxed text-muted-foreground">
          Generate comprehensive construction estimates, BOQs, and cost breakdowns in PDF or Excel
          (CSV) formats.
        </p>
      </header>

      <div className="mt-10 grid gap-6 lg:grid-cols-[1fr_2fr]">
        <section className="rounded-lg border border-border bg-card p-6 shadow-sm h-fit">
          <h2 className="text-sm font-semibold uppercase tracking-widest text-muted-foreground">
            Project Information
          </h2>
          <div className="mt-6 space-y-4">
            <label className="block">
              <span className="text-sm font-medium">Project Name</span>
              <input
                value={project.name}
                onChange={(e) => updateActiveProject({ name: e.target.value })}
                className="mt-1 w-full rounded-md border border-input bg-background px-3 py-2 text-sm"
              />
            </label>
            <label className="block">
              <span className="text-sm font-medium">Client Name</span>
              <input
                value={project.clientName || ""}
                onChange={(e) => updateActiveProject({ clientName: e.target.value })}
                className="mt-1 w-full rounded-md border border-input bg-background px-3 py-2 text-sm"
              />
            </label>
            <label className="block">
              <span className="text-sm font-medium">Project Location</span>
              <input
                value={project.location || ""}
                onChange={(e) => updateActiveProject({ location: e.target.value })}
                className="mt-1 w-full rounded-md border border-input bg-background px-3 py-2 text-sm"
              />
            </label>
          </div>
        </section>

        <section className="rounded-lg border border-border bg-card p-8 shadow-sm flex flex-col items-center justify-center text-center">
          <div className="rounded-full bg-primary/10 p-4 mb-6">
            <FileSpreadsheet size={48} className="text-primary" />
          </div>
          <h2 className="text-2xl font-bold">Export your report</h2>
          <p className="mt-2 text-muted-foreground max-w-md">
            Download a professional PDF document or a CSV spreadsheet containing all your project's
            estimates and BOQ.
          </p>
          <div className="mt-8 flex flex-col sm:flex-row gap-4">
            <button
              onClick={downloadPdf}
              disabled={project.items.length === 0}
              className="inline-flex items-center justify-center gap-2 rounded-md bg-primary px-6 py-3 text-sm font-semibold text-primary-foreground transition-opacity hover:opacity-90 disabled:opacity-50"
            >
              <Download size={18} /> Export as PDF
            </button>
            <button
              onClick={downloadCsv}
              disabled={project.items.length === 0}
              className="inline-flex items-center justify-center gap-2 rounded-md border border-border bg-background px-6 py-3 text-sm font-semibold transition-colors hover:bg-secondary disabled:opacity-50"
            >
              <FileSpreadsheet size={18} /> Export as CSV
            </button>
          </div>
        </section>
      </div>
    </Page>
  );
}
