/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AboutRouteImport } from './routes/about'
import { Route as BoqRouteImport } from './routes/boq'
import { Route as CostEstimateRouteImport } from './routes/cost-estimate'
import { Route as DashboardRouteImport } from './routes/dashboard'
import { Route as MaterialPricesRouteImport } from './routes/material-prices'
import { Route as PlanUploadRouteImport } from './routes/plan-upload'
import { Route as ProjectRouteImport } from './routes/project'
import { Route as ReportsRouteImport } from './routes/reports'
import { Route as SettingsRouteImport } from './routes/settings'
import { Route as SubscriptionRouteImport } from './routes/subscription'
import { Route as TakeoffRouteImport } from './routes/takeoff'
import { Route as CalculatorsIndexRouteImport } from './routes/calculators.index'
import { Route as CalculatorsBrickRouteImport } from './routes/calculators.brick'
import { Route as CalculatorsCementRouteImport } from './routes/calculators.cement'
import { Route as CalculatorsConcreteRouteImport } from './routes/calculators.concrete'
import { Route as CalculatorsPaintRouteImport } from './routes/calculators.paint'
import { Route as CalculatorsSteelRouteImport } from './routes/calculators.steel'
import { Route as CalculatorsTileRouteImport } from './routes/calculators.tile'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AboutRoute = AboutRouteImport.update({
  id: '/about',
  path: '/about',
  getParentRoute: () => rootRouteImport,
} as any)
const BoqRoute = BoqRouteImport.update({
  id: '/boq',
  path: '/boq',
  getParentRoute: () => rootRouteImport,
} as any)
const CostEstimateRoute = CostEstimateRouteImport.update({
  id: '/cost-estimate',
  path: '/cost-estimate',
  getParentRoute: () => rootRouteImport,
} as any)
const DashboardRoute = DashboardRouteImport.update({
  id: '/dashboard',
  path: '/dashboard',
  getParentRoute: () => rootRouteImport,
} as any)
const MaterialPricesRoute = MaterialPricesRouteImport.update({
  id: '/material-prices',
  path: '/material-prices',
  getParentRoute: () => rootRouteImport,
} as any)
const PlanUploadRoute = PlanUploadRouteImport.update({
  id: '/plan-upload',
  path: '/plan-upload',
  getParentRoute: () => rootRouteImport,
} as any)
const ProjectRoute = ProjectRouteImport.update({
  id: '/project',
  path: '/project',
  getParentRoute: () => rootRouteImport,
} as any)
const ReportsRoute = ReportsRouteImport.update({
  id: '/reports',
  path: '/reports',
  getParentRoute: () => rootRouteImport,
} as any)
const SettingsRoute = SettingsRouteImport.update({
  id: '/settings',
  path: '/settings',
  getParentRoute: () => rootRouteImport,
} as any)
const SubscriptionRoute = SubscriptionRouteImport.update({
  id: '/subscription',
  path: '/subscription',
  getParentRoute: () => rootRouteImport,
} as any)
const TakeoffRoute = TakeoffRouteImport.update({
  id: '/takeoff',
  path: '/takeoff',
  getParentRoute: () => rootRouteImport,
} as any)
const CalculatorsIndexRoute = CalculatorsIndexRouteImport.update({
  id: '/calculators/',
  path: '/calculators/',
  getParentRoute: () => rootRouteImport,
} as any)
const CalculatorsBrickRoute = CalculatorsBrickRouteImport.update({
  id: '/calculators/brick',
  path: '/calculators/brick',
  getParentRoute: () => rootRouteImport,
} as any)
const CalculatorsCementRoute = CalculatorsCementRouteImport.update({
  id: '/calculators/cement',
  path: '/calculators/cement',
  getParentRoute: () => rootRouteImport,
} as any)
const CalculatorsConcreteRoute = CalculatorsConcreteRouteImport.update({
  id: '/calculators/concrete',
  path: '/calculators/concrete',
  getParentRoute: () => rootRouteImport,
} as any)
const CalculatorsPaintRoute = CalculatorsPaintRouteImport.update({
  id: '/calculators/paint',
  path: '/calculators/paint',
  getParentRoute: () => rootRouteImport,
} as any)
const CalculatorsSteelRoute = CalculatorsSteelRouteImport.update({
  id: '/calculators/steel',
  path: '/calculators/steel',
  getParentRoute: () => rootRouteImport,
} as any)
const CalculatorsTileRoute = CalculatorsTileRouteImport.update({
  id: '/calculators/tile',
  path: '/calculators/tile',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/boq': typeof BoqRoute
  '/cost-estimate': typeof CostEstimateRoute
  '/dashboard': typeof DashboardRoute
  '/material-prices': typeof MaterialPricesRoute
  '/plan-upload': typeof PlanUploadRoute
  '/project': typeof ProjectRoute
  '/reports': typeof ReportsRoute
  '/settings': typeof SettingsRoute
  '/subscription': typeof SubscriptionRoute
  '/takeoff': typeof TakeoffRoute
  '/calculators/brick': typeof CalculatorsBrickRoute
  '/calculators/cement': typeof CalculatorsCementRoute
  '/calculators/concrete': typeof CalculatorsConcreteRoute
  '/calculators/paint': typeof CalculatorsPaintRoute
  '/calculators/steel': typeof CalculatorsSteelRoute
  '/calculators/tile': typeof CalculatorsTileRoute
  '/calculators/': typeof CalculatorsIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/boq': typeof BoqRoute
  '/cost-estimate': typeof CostEstimateRoute
  '/dashboard': typeof DashboardRoute
  '/material-prices': typeof MaterialPricesRoute
  '/plan-upload': typeof PlanUploadRoute
  '/project': typeof ProjectRoute
  '/reports': typeof ReportsRoute
  '/settings': typeof SettingsRoute
  '/subscription': typeof SubscriptionRoute
  '/takeoff': typeof TakeoffRoute
  '/calculators/brick': typeof CalculatorsBrickRoute
  '/calculators/cement': typeof CalculatorsCementRoute
  '/calculators/concrete': typeof CalculatorsConcreteRoute
  '/calculators/paint': typeof CalculatorsPaintRoute
  '/calculators/steel': typeof CalculatorsSteelRoute
  '/calculators/tile': typeof CalculatorsTileRoute
  '/calculators': typeof CalculatorsIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/boq': typeof BoqRoute
  '/cost-estimate': typeof CostEstimateRoute
  '/dashboard': typeof DashboardRoute
  '/material-prices': typeof MaterialPricesRoute
  '/plan-upload': typeof PlanUploadRoute
  '/project': typeof ProjectRoute
  '/reports': typeof ReportsRoute
  '/settings': typeof SettingsRoute
  '/subscription': typeof SubscriptionRoute
  '/takeoff': typeof TakeoffRoute
  '/calculators/brick': typeof CalculatorsBrickRoute
  '/calculators/cement': typeof CalculatorsCementRoute
  '/calculators/concrete': typeof CalculatorsConcreteRoute
  '/calculators/paint': typeof CalculatorsPaintRoute
  '/calculators/steel': typeof CalculatorsSteelRoute
  '/calculators/tile': typeof CalculatorsTileRoute
  '/calculators/': typeof CalculatorsIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/about'
    | '/boq'
    | '/cost-estimate'
    | '/dashboard'
    | '/material-prices'
    | '/plan-upload'
    | '/project'
    | '/reports'
    | '/settings'
    | '/subscription'
    | '/takeoff'
    | '/calculators/brick'
    | '/calculators/cement'
    | '/calculators/concrete'
    | '/calculators/paint'
    | '/calculators/steel'
    | '/calculators/tile'
    | '/calculators/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/about'
    | '/boq'
    | '/cost-estimate'
    | '/dashboard'
    | '/material-prices'
    | '/plan-upload'
    | '/project'
    | '/reports'
    | '/settings'
    | '/subscription'
    | '/takeoff'
    | '/calculators/brick'
    | '/calculators/cement'
    | '/calculators/concrete'
    | '/calculators/paint'
    | '/calculators/steel'
    | '/calculators/tile'
    | '/calculators'
  id:
    | '__root__'
    | '/'
    | '/about'
    | '/boq'
    | '/cost-estimate'
    | '/dashboard'
    | '/material-prices'
    | '/plan-upload'
    | '/project'
    | '/reports'
    | '/settings'
    | '/subscription'
    | '/takeoff'
    | '/calculators/brick'
    | '/calculators/cement'
    | '/calculators/concrete'
    | '/calculators/paint'
    | '/calculators/steel'
    | '/calculators/tile'
    | '/calculators/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AboutRoute: typeof AboutRoute
  BoqRoute: typeof BoqRoute
  CostEstimateRoute: typeof CostEstimateRoute
  DashboardRoute: typeof DashboardRoute
  MaterialPricesRoute: typeof MaterialPricesRoute
  PlanUploadRoute: typeof PlanUploadRoute
  ProjectRoute: typeof ProjectRoute
  ReportsRoute: typeof ReportsRoute
  SettingsRoute: typeof SettingsRoute
  SubscriptionRoute: typeof SubscriptionRoute
  TakeoffRoute: typeof TakeoffRoute
  CalculatorsBrickRoute: typeof CalculatorsBrickRoute
  CalculatorsCementRoute: typeof CalculatorsCementRoute
  CalculatorsConcreteRoute: typeof CalculatorsConcreteRoute
  CalculatorsPaintRoute: typeof CalculatorsPaintRoute
  CalculatorsSteelRoute: typeof CalculatorsSteelRoute
  CalculatorsTileRoute: typeof CalculatorsTileRoute
  CalculatorsIndexRoute: typeof CalculatorsIndexRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/about': {
      id: '/about'
      path: '/about'
      fullPath: '/about'
      preLoaderRoute: typeof AboutRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/boq': {
      id: '/boq'
      path: '/boq'
      fullPath: '/boq'
      preLoaderRoute: typeof BoqRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/cost-estimate': {
      id: '/cost-estimate'
      path: '/cost-estimate'
      fullPath: '/cost-estimate'
      preLoaderRoute: typeof CostEstimateRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/dashboard': {
      id: '/dashboard'
      path: '/dashboard'
      fullPath: '/dashboard'
      preLoaderRoute: typeof DashboardRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/material-prices': {
      id: '/material-prices'
      path: '/material-prices'
      fullPath: '/material-prices'
      preLoaderRoute: typeof MaterialPricesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/plan-upload': {
      id: '/plan-upload'
      path: '/plan-upload'
      fullPath: '/plan-upload'
      preLoaderRoute: typeof PlanUploadRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/project': {
      id: '/project'
      path: '/project'
      fullPath: '/project'
      preLoaderRoute: typeof ProjectRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/reports': {
      id: '/reports'
      path: '/reports'
      fullPath: '/reports'
      preLoaderRoute: typeof ReportsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/settings': {
      id: '/settings'
      path: '/settings'
      fullPath: '/settings'
      preLoaderRoute: typeof SettingsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/subscription': {
      id: '/subscription'
      path: '/subscription'
      fullPath: '/subscription'
      preLoaderRoute: typeof SubscriptionRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/takeoff': {
      id: '/takeoff'
      path: '/takeoff'
      fullPath: '/takeoff'
      preLoaderRoute: typeof TakeoffRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/calculators/': {
      id: '/calculators/'
      path: '/calculators'
      fullPath: '/calculators/'
      preLoaderRoute: typeof CalculatorsIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/calculators/brick': {
      id: '/calculators/brick'
      path: '/calculators/brick'
      fullPath: '/calculators/brick'
      preLoaderRoute: typeof CalculatorsBrickRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/calculators/cement': {
      id: '/calculators/cement'
      path: '/calculators/cement'
      fullPath: '/calculators/cement'
      preLoaderRoute: typeof CalculatorsCementRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/calculators/concrete': {
      id: '/calculators/concrete'
      path: '/calculators/concrete'
      fullPath: '/calculators/concrete'
      preLoaderRoute: typeof CalculatorsConcreteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/calculators/paint': {
      id: '/calculators/paint'
      path: '/calculators/paint'
      fullPath: '/calculators/paint'
      preLoaderRoute: typeof CalculatorsPaintRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/calculators/steel': {
      id: '/calculators/steel'
      path: '/calculators/steel'
      fullPath: '/calculators/steel'
      preLoaderRoute: typeof CalculatorsSteelRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/calculators/tile': {
      id: '/calculators/tile'
      path: '/calculators/tile'
      fullPath: '/calculators/tile'
      preLoaderRoute: typeof CalculatorsTileRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AboutRoute: AboutRoute,
  BoqRoute: BoqRoute,
  CostEstimateRoute: CostEstimateRoute,
  DashboardRoute: DashboardRoute,
  MaterialPricesRoute: MaterialPricesRoute,
  PlanUploadRoute: PlanUploadRoute,
  ProjectRoute: ProjectRoute,
  ReportsRoute: ReportsRoute,
  SettingsRoute: SettingsRoute,
  SubscriptionRoute: SubscriptionRoute,
  TakeoffRoute: TakeoffRoute,
  CalculatorsBrickRoute: CalculatorsBrickRoute,
  CalculatorsCementRoute: CalculatorsCementRoute,
  CalculatorsConcreteRoute: CalculatorsConcreteRoute,
  CalculatorsPaintRoute: CalculatorsPaintRoute,
  CalculatorsSteelRoute: CalculatorsSteelRoute,
  CalculatorsTileRoute: CalculatorsTileRoute,
  CalculatorsIndexRoute: CalculatorsIndexRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
